You can now set SpecMap.raiseExceptions = true and, if runtime exceptions are caught, they will be thrown.  The test suite will stop, but you'll have a stacktrace.

diff --git a/script/run_specs b/script/run_specs
--- a/script/run_specs
+++ b/script/run_specs
@@ -7,3 +7,7 @@ echo "-> Exit code ($?) should be 0"
 echo "-> Running Failing Spec (should have all kinds of specs)"
 dart_bin spec/run_failing_spec.dart
 echo "-> Exit code ($?) should not be 0"
+
+echo "-> Running Failing Spec that Raises Exceptions (should blow up with a stacktrace)"
+dart_bin spec/run_failing_raising_exceptions_spec.dart
+echo "-> Exit code ($?) should not be 0"
